// Resource definitions for chat settings dialog
// Defines dialog IDs and control constants for the chat configuration UI
// including checkboxes, edit controls, and spin controls for settings

#ifndef PLUGINNPPOPENAI_CHATSETTINGSRESOURCE_H
#define PLUGINNPPOPENAI_CHATSETTINGSRESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif

#define IDD_PLUGINNPPOPENAI_CHATSETTINGS 2600
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_USECHAT_CAPTION (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 10)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_USECHAT_CHECK (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 20)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_LIMIT_STATIC (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 30)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_LIMIT_EDIT (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 40)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_LIMIT_UPDOWN (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 50)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_INFO (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 60)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_OK (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 70)
#define ID_PLUGINNPPOPENAI_CHATSETTINGS_CANCEL (IDD_PLUGINNPPOPENAI_CHATSETTINGS + 80)

#endif // PLUGINNPPOPENAI_CHATSETTINGSRESOURCE_H
