// Resource definitions for the loading dialog
// Defines dialog IDs and control constants for the progress/loading UI
// shown during API requests and streaming responses

#ifndef PLUGINNPPOPENAI_LOADERRESOURCE_H
#define PLUGINNPPOPENAI_LOADERRESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif

#define IDD_PLUGINNPPOPENAI_LOADING 2500
#define ID_PLUGINNPPOPENAI_LOADING_STATIC (IDD_PLUGINNPPOPENAI_LOADING + 10)
#define ID_PLUGINNPPOPENAI_LOADING_ESTIMATE (IDD_PLUGINNPPOPENAI_LOADING + 11)
#define ID_PLUGINNPPOPENAI_LOADING_PROGRESS (IDD_PLUGINNPPOPENAI_LOADING + 20)
#define ID_PLUGINNPPOPENAI_LOADING_CANCEL (IDD_PLUGINNPPOPENAI_LOADING + 30)

#endif // PLUGINNPPOPENAI_LOADERRESOURCE_H
